-- MySQL Script generated by MySQL Workbench
-- Tue Jul 26 02:52:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema businessmind
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `businessmind` ;

-- -----------------------------------------------------
-- Schema businessmind
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `businessmind` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `businessmind` ;

-- -----------------------------------------------------
-- Table `businessmind`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessmind`.`customer` (
  `id`  NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `surname` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `businessmind`.`insurance_agency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessmind`.`insurance_agency` (
  `id`  NOT NULL,
  `agency_name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `manager_first_name` VARCHAR(255) NULL DEFAULT NULL,
  `manager_last_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `businessmind`.`high_level_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessmind`.`high_level_manager` (
  `id`  NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `surname` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `businessmind`.`policy_report_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `businessmind`.`policy_report_data` (
  `id`  NOT NULL,
  `end_year`  NULL DEFAULT NULL,
  `endorsement`  NULL DEFAULT NULL,
  `start_year`  NULL DEFAULT NULL,
  `total_profit`  NULL DEFAULT NULL,
  `customer_id`  NULL DEFAULT NULL,
  `insurance_agency_id`  NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKmuht2tslueywxj2njoc2iy55y` (`customer_id` ASC) VISIBLE,
  INDEX `FK5jo1rc859hyi2pqv99blwas8y` (`insurance_agency_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
